[tox]
envlist = py311, py312, py313, py314, pipmain, pipdoc
skip_missing_interpreters = true
isolated_build = false


[testenv]
changedir = {envtmpdir}

[testenv:py{311,312,313,314}]
description = Pytest (poetry install)
allowlist_externals = poetry
skip_install = true
setenv =
  COVERAGE_FILE = {envtmpdir}/.coverage
commands_pre =
    poetry install --with dev
commands =
    poetry run poe test -rootdir {toxinidir} {posargs}

# pip test: main package
[testenv:pipmain]
description = Pip install test (no poetry)
deps =
    pytest
    pytest-cov
setenv =
  COVERAGE_FILE = {envtmpdir}/.coverage
commands =
    python -m pip install {toxinidir}
    pytest {toxinidir} {posargs}

# pip test: docs
[testenv:pipdoc]
description = Pip install docs test (no poetry)
commands =
    python -m pip install {toxinidir}[doc]
    python -m sphinx.cmd.build -b html {toxinidir}/doc documentation
    python -c "from pathlib import Path; assert Path('documentation/index.html').exists()"
