[tox]
envlist = py311, py312, py313, py314
skip_missing_interpreters = true
isolated_build = false


[testenv]
changedir = {envtmpdir}
allowlist_externals = poetry
skip_install = true
setenv =
  COVERAGE_FILE = {envtmpdir}/.coverage
commands_pre =
    poetry install --with dev
commands =
    poetry run poe test {toxinidir} {posargs}
