[tox]
envlist = py311, py312, py313, py314
skip_missing_interpreters = true
isolated_build = false


[testenv]
changedir = {toxinidir}/tox_test_{envname}
allowlist_externals = poetry
skip_install = true
commands_pre =
    poetry install --with dev
commands =
    poetry run poe test {toxinidir} {posargs}
